markdown: rdiscount
permalink: /:title
destination: ./_site
paginate: 10
include: [.htaccess]
exclude: [
          Gruntfile.js,
          grunt,
          node_modules/,
          old_img/,
          package.json,
          robots.txt,
          css/styles.css,
          assets/,
          ]
