markdown: rdiscount
permalink: /:title
destination: ./_site
paginate: 10
include: [.htaccess]
exclude: [
  assets,
  backbone,
  bower_components,
  css/styles.css,
  Gruntfile.js,
  grunt,
  js/cacheTest.js,
  node_modules,
  old_img,
  package.json,
  robots.txt
]