name: kaidez
description: kaidez.com / Tutorials and articles about Web Development
url: http://kaidez.com
source:      .
destination: ./_site
markdown: rdiscount
permalink: /:title
destination: ./_site
paginate: 10
paginate_path: "pages/page:num"
exclude: [
  .ftppass,
  assets,
  backbone,
  bower.json,
  bower_components,
  requireBuildOut,
  Capfile,
  config,
  Gruntfile.js,
  grunt,
  jekyllOutput.html,
  kaidezSiteNotes.txt,
  kaidezcom.WPExport.xml,
  kaidezSiteNotes.txt,
  LICENSE-MIT,
  node_modules,
  package.json,
  prototypeTest,
  README.md,
  old_img,
  old_js,
  r.js,
  repo*.png,
  terminalShot*.png,
  _posts/2014-09-17-lynda-kaidez.md
]
