name: kaidez
description: kaidez.com / Tutorials and articles about Web Development
url: http://kaidez.com
markdown: rdiscount
permalink: /:title
destination: ./_site
paginate: 10
include: [.htaccess]
exclude: [
  assets,
  backbone,
  bower_components,
  css/styles.css,
  Gruntfile.js,
  grunt,
  jsBuildOut,
  kaidezSiteNotes.txt,
  node_modules,
  package.json,
  old_img,
  old_js,
  r.js,
  robots.txt
]